name = "site-react"
account_id = "e4e4d4672c3b96cb4316483675a57321"
compatibility_date = "2025-06-18"

# Learn more at https://developers.cloudflare.com/workers/runtime-apis/nodejs/
# We recommend to always use the latest supported version of the Workers runtime.
# https://developers.cloudflare.com/workers/platform/versions/#workers-runtime
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[site]
bucket = ".open-next/assets"

# Uncomment this when the domain is active in this account to auto-route.
# routes = [ { pattern = "nyoom.engineering/*" } ]